export default [
    {
        id: 0,
        img: '/product-1.jpg',
        name:'SSTR N 2005',
        price: 41.0,
        category: ['shoes'],
        sale: false,
    },
    {
        id: 1,
        img: '/product-2.jpg',
        name:'Humanrace Samba Pharrell Williams',
        price: 38.0,
        category: ['shoes'],
        sale: false,
    },
    {
        id: 2,
        img: '/product-3.jpg',
        name:'DAILY 4.0',
        price: 29.0,
        category: ['shoes'],
        sale: true,
    },
    {
        id: 3,
        img: '/product-4.jpg',
        name:'GRAND COURT 2.0',
        price: 23.0,
        category: ['shoes'],
        sale: false,
    },
    {
        id: 4,
        img: '/product-5.jpg',
        name:'COPA PURE 2 CLUB FXG',
        price: 50.0,
        category: ['shoes'],
        sale: false,
    },
    {
        id: 5,
        img: '/product-6.jpg',
        name:'SAMBA OG',
        price: 40.0,
        category: ['shoes'],
        sale: true,
    },
    {
        id: 6,
        img: '/product-7.jpg',
        name:'3-STRIPES TEE',
        price: 80.0,
        category: ['t-shirts'],
        sale: true,
    },
    {
        id: 7,
        img: '/product-8.jpg',
        name:'BASIC BOS TEE',
        price: 65.0,
        category: ['t-shirts'],
        sale: false,
    },
    {
        id: 8,
        img: '/product-9.jpg',
        name:'AMPLIFIER',
        price: 79.99,
        category: ['t-shirts'],
        sale: true,
    },
    {
        id: 9,
        img: '/product-10.jpg',
        name:'ADICOLOR CLASSICS 3-STRIPES',
        price: 129.99,
        category: ['t-shirts'],
        sale: false,
    },
    {
        id: 10,
        img: '/product-11.jpg',
        name:'M BOOST ROCKET',
        price: 89.99,
        category: ['t-shirts'],
        sale: false,
    },
    {
        id: 11,
        img: '/product-12.jpg',
        name:'LEMON TREFOIL',
        price: 129.99,
        category: ['t-shirts'],
        sale: true,
    },
]