export default [
    {
        id: 0,
        img: '/product-1.jpg',
        name:'SSTR N 2005',
        price: 41.0,
        category: ['shoes'],
        sale: false,
    },
    {
        id: 1,
        img: '/product-2.jpg',
        name:'Humanrace Samba Pharrell Williams',
        price: 38.0,
        category: ['shoes'],
        sale: false,
    },
    {
        id: 2,
        img: '/product-3.jpg',
        name:'DAILY 4.0',
        price: 29.0,
        category: ['shoes'],
        sale: true,
    },
    {
        id: 3,
        img: '/product-4.jpg',
        name:'GRAND COURT 2.0',
        price: 23.0,
        category: ['shoes'],
        sale: false,
    },
    {
        id: 4,
        img: '/product-5.jpg',
        name:'COPA PURE 2 CLUB FXG',
        price: 50.0,
        category: ['shoes'],
        sale: false,
    },
    {
        id: 5,
        img: '/product-6.jpg',
        name:'SAMBA OG',
        price: 40.0,
        category: ['shoes'],
        sale: true,
    },
    {
        id: 6,
        img: '/product-7.jpg',
        name:'3-STRIPES TEE',
        price: 80.0,
        category: ['t-shirts'],
        sale: true,
    },
    {
        id: 7,
        img: '/product-8.jpg',
        name:'BASIC BOS TEE',
        price: 65.0,
        category: ['t-shirts'],
        sale: false,
    },
    {
        id: 8,
        img: '/product-9.jpg',
        name:'AMPLIFIER',
        price: 79.99,
        category: ['t-shirts'],
        sale: true,
    },
    {
        id: 9,
        img: '/product-10.jpg',
        name:'ADICOLOR CLASSICS 3-STRIPES',
        price: 129.99,
        category: ['t-shirts'],
        sale: false,
    },
    {
        id: 10,
        img: '/product-11.jpg',
        name:'M BOOST ROCKET',
        price: 89.99,
        category: ['t-shirts'],
        sale: false,
    },
    {
        id: 11,
        img: '/product-12.jpg',
        name:'LEMON TREFOIL',
        price: 129.99,
        category: ['t-shirts'],
        sale: true,
    },
    {
        id: 12,
        img: '/product-13.jpg',
        name:'MALHA F50',
        price: 449.49,
        category: ['coats'],
        sale: false,
    },
    {
        id: 13,
        img: '/product-14.jpg',
        name:'CRF DNA WB',
        price: 699.99,
        category: ['coats'],
        sale: true,
    },
    {
        id: 14,
        img: '/product-15.jpg',
        name:'CAPUZ DOWN VARILITE',
        price: 999.99,
        category: ['coats'],
        sale: false,
    },
    {
        id: 15,
        img: '/product-16.jpg',
        name:'BOMBER ESSENTIALS INSULATED',
        price: 599.99,
        category: ['coats'],
        sale: false,
    },
    {
        id: 16,
        img: '/product-17.jpg',
        name:'A.BLONDEY CHORE SKATEBOARDING',
        price: 1299.99,
        category: ['coats'],
        sale: true,
    },
    {
        id: 17,
        img: '/product-18.jpg',
        name:'LETTERMAN Y-3',
        price: 490.00,
        category: ['coats'],
        sale: false,
    },
    {
        id: 18,
        img: '/product-19.jpg',
        name:'AEROREADY SERENO SLIM TAPERED CUT 3-STRIPES',
        price: 199.99,
        category: ['pants'],
        sale: false,
    },
    {
        id: 19,
        img: '/product-20.jpg',
        name:'TRAVEL CR FLAMENGO',
        price: 279.99,
        category: ['pants'],
        sale: true,
    },
    {
        id: 20,
        img: '/product-21.jpg',
        name:'OWN THE RUN SOFT SHELL',
        price: 499.99,
        category: ['pants'],
        sale: false,
    },
    {
        id: 21,
        img: '/product-22.jpg',
        name:'SPORTSWEAR FUTURE ICONS 3-STRIPES',
        price: 399.99,
        category: ['pants'],
        sale: true,
    },
    {
        id: 22,
        img: '/product-23.jpg',
        name:'ADIDAS SPRT COLORBLOCK',
        price: 349.99,
        category: ['pants'],
        sale: false,
    },
    {
        id: 23,
        img: '/product-24.jpg',
        name:'DAME 8 INNOVATION',
        price: 229.99,
        category: ['pants'],
        sale: false,
    },
]